image: gitpod/workspace-java-17

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack

tasks:
- init: |
    apt-get install -y hey
    apt-get install -y openjdk-11-jre  
    mvn dependency:go-offline package -DskipTests
    cat "127.0.0.1 kafka" > /etc/hosts
