image: gitpod/workspace-java-17

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack

tasks:
- init: |
    sudo apt-get install -y hey
    mvn dependency:go-offline package -DskipTests
    echo "127.0.0.1 kafka" | sudo tee -a /etc/hosts
